### ISSUE TITLE
Cannot send custom tags to Loggly

### ISSUE THREAD

**Issue by emptyarray** [tony19/timber-loggly#1]
Currently it appears that it is impossible to send Loggly's tags. This is also an issue with loggly-client.
Loggly expects tags to be in the URL, like this one from their docs: ```http://logs-01.loggly.com/bulk/CUSTOMER_TOKEN/tag/sample```.

Ideally timer-loggly and loggly-client would support sending an array of tags to Loggly. On the loggly-client side, it would be something like changing: ```@POST("/inputs/{token}/tag/http/")``` to ```@POST("/inputs/{token}/tag/{tags}/")```, and then sending through a serialized tags array.

Thanks for taking a look. Let me know if there is another way of sending tags that I'm missing.

**Comment by tony19** [comment]
Yep, I was planning on adding that. I just whipped something up in https://github.com/tony19/loggly-client/commit/4e48b5a75823036f8005be004a0c2b0948e9bdfa

I'll bring this into timber-loggly some time this week.

**Comment by emptyarray** [comment]
Great, looking forward to it.

**Comment by tony19** [comment]
Fixed in https://github.com/tony19/timber-loggly/commit/02ae590afd5fce24815e4b6c86fa8643bd2306ba
