### ISSUE TITLE
Handle unintentional interpretation of "%..." string contents as formatters.

### ISSUE THREAD

**Issue by josefdlange** [tony19/timber-loggly#8]
Some of the data I log has, interspersed with it, strings that have a `%` in them, typically followed by some alphanumeric characters. In these cases, `timber-loggly`'s logic ends up interpreting those as string formatters, and when it gets passed into the `toJson` method, everything blows up. I'm going to try some work on this to fix it shortly and see if I can yield some positive results.

**Comment by tony19** [comment]
@josefdlange Does be311fd match your use case?

**Comment by josefdlange** [comment]
Looks like it to me.

**Comment by hastoukopsaro** [comment]
Any updates on this guys?

**Comment by mateusgrb** [comment]
Hey @tony19, any plans to fix that soon? This is causing us issues in production.

**Comment by tony19** [comment]
Fixed by upgrade to Timber 4.1.2 in edf8486b6dda091d09972f87b7e128acb3d0e1fd

**Comment by tony19** [comment]
Try [timber-loggly-1.0.2](https://github.com/tony19/timber-loggly/releases/tag/timber-loggly-1.0.2)

**Comment by mateusgrb** [comment]
@tony19 Thanks for the help. Would it be possible to upload 1.0.2 to maven/gradle? I added JARs below in addition to timber-loggly-1.0.2:

- loggly-client-1.0.3
- retrofit-1.9.0
- gson-2.3.1

That got my project compiled and builded, but upon running no logs are sent to loggly. As it works when I use timber-loggly-1.0.1 via gradle, I believe it's a dependency issue, so being able to use it via Gradle would help tons!

**Comment by mateusgrb** [comment]
Nevermind, I managed to get 1.0.2 working using JitPack. The logs were actually being sent but without the tags. I learned that in this version you need to call the tag() method on LogglyTree and not on Timber anymore. Would be nice to have the README updated to reflect those changes!
